run:
    restore_from: continue
    visualize: append
    do: ['train','eval','visualize']
    gpu_id: 0
log:
    project: montero_model_rep
    group: intervene_betavae_pendulum
    wandb_mode: run
    level: info
data:
    name: pendulum
    num_workers: 12
    phase: train
train:
    epochs: 25
    lr: 0.0001
    batch_size: 64
    checkpoint_every: 50
    checkpoint_first: 1
    loss: intervene_betavae
    rec_dist: bernoulli
betavae:
    beta: 1.0
    log_components: False
model:
    name: intervene_vae_montero_small
vae_locatello:
    latent_dim: 10
eval:
    batch_size: 1024
    mode: last
