run:
    restore_from: continue
    visualize: append
    do: ['train','eval','visualize']
    gpu_id: 0
    restore_hyperparams: False
log:
    project: montero_model_rep
    group: intervene_betavae_celeba
    wandb_mode: run
    level: info
data:
    name: celeba
    num_workers: 12
train:
    epochs: 60
    lr: 0.0001
    batch_size: 1024
    checkpoint_every: 50
    checkpoint_first: 1
    loss: intervene_betavae
    rec_dist: bernoulli #gaussian #bernoulli
betavae:
    beta: 1.0
    log_components: False
model:
    name: intervene_vae_montero_small
vae_locatello:
    latent_dim: 32
eval:
    batch_size: 1024
    mode: last
    metrics:
        ['kld', 'fos', 'reconstruction_error']
rect:
    rect_coeff: 0.1
shuffled_betavae:
    shuffled_coeff: 1.0
# scheduler:
#     name: multistep
#     tau: [1000,]
#     gamma: [0.1,]
